version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./ingest:/app/ingest
    environment:
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paralegal
      - POSTGRES_USER=paralegal
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-paralegal}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - postgres
      - redis
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=paralegal
      - POSTGRES_USER=paralegal
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-paralegal}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
    volumes:
      - ./certificates:/app/certificates:ro
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zeddq1/volumes/postgres
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zeddq1/volumes/redis
  qdrant_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zeddq1/volumes/qdrant
