version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./ingest:/app/ingest
      - /app/app/__pycache__
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paralegal
      - POSTGRES_USER=paralegal
      - POSTGRES_PASSWORD=paralegal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - postgres
      - redis
      - qdrant
    command: uvicorn app.routes:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=paralegal
      - POSTGRES_USER=paralegal
      - POSTGRES_PASSWORD=paralegal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=zeddq1@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps
    depends_on:
      - api
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/code/cywil/volumes/postgres
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/code/cywil/volumes/redis
  qdrant_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/code/cywil/volumes/qdrant
