"""add created_by_user column to case

Revision ID: 00df3e0ab26c
Revises: 
Create Date: 2025-07-06 00:26:53.710257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '00df3e0ab26c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('created_by_id', sa.String(), nullable=True))
    # op.alter_column('cases', 'description',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('cases', 'status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('cases', 'currency',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.create_foreign_key('fk_cases_created_by_id_users', 'cases', 'users', ['created_by_id'], ['id'])
    # op.drop_column('cases', 'title')
    # op.alter_column('deadlines', 'deadline_type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('deadlines', 'description',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('deadlines', 'is_court_deadline',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.alter_column('deadlines', 'is_extendable',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.alter_column('deadlines', 'status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('deadlines', 'reminder_days_before',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('deadlines', 'reminder_sent',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.alter_column('deadlines', 'case_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('documents', 'document_type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('documents', 'content',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('documents', 'status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('documents', 'case_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('form_templates', 'summary',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('form_templates', 'content',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # op.alter_column('form_templates', 'variables',
    #            existing_type=postgresql.ARRAY(sa.VARCHAR()),
    #            type_=sa.JSON(),
    #            nullable=True)
    # op.alter_column('form_templates', 'usage_count',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('form_templates', 'qdrant_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # op.drop_index(op.f('ix_form_templates_id'), table_name='form_templates')
    # op.drop_index(op.f('ix_form_templates_qdrant_id'), table_name='form_templates')
    # op.create_unique_constraint('uq_form_templates_qdrant_id', 'form_templates', ['qdrant_id'])
    # op.alter_column('notes', 'note_type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('notes', 'content',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            nullable=False)
    # op.alter_column('notes', 'billable',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.alter_column('statute_chunks', 'text',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statute_chunks', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notes', 'billable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notes', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('notes', 'note_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_form_templates_qdrant_id', 'form_templates', type_='unique')
    op.create_index(op.f('ix_form_templates_qdrant_id'), 'form_templates', ['qdrant_id'], unique=True)
    op.create_index(op.f('ix_form_templates_id'), 'form_templates', ['id'], unique=False)
    op.alter_column('form_templates', 'qdrant_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('form_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('form_templates', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('form_templates', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('form_templates', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'case_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deadlines', 'case_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deadlines', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('deadlines', 'reminder_days_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deadlines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deadlines', 'is_extendable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('deadlines', 'is_court_deadline',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('deadlines', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('deadlines', 'deadline_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('cases', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_cases_created_by_id_users', 'cases', type_='foreignkey')
    op.alter_column('cases', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cases', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('cases', 'created_by_id')
    # ### end Alembic commands ###
