apiVersion: v1
kind: Secret
metadata:
  name: ai-paralegal-secrets
  namespace: ai-paralegal
type: Opaque
stringData:
  # PostgreSQL credentials
  POSTGRES_USER: "paralegal"
  POSTGRES_PASSWORD: "paralegal"
  
  # Redis credentials
  REDIS_PASSWORD: "paralegal"
  REDIS_URL: "redis://:paralegal@redis-service:6379/0"
  
  # Qdrant credentials
  QDRANT_API_KEY: "paralegal"
  
  # Database URL for application
  DATABASE_URL: "postgresql+asyncpg://paralegal:paralegal@postgres-service:5432/paralegal_prod"
  
  # Application secret key
  SECRET_KEY: "paralegal-secret-key-change-in-production"
  
  # Admin token
  ADMIN_TOKEN: "paralegal-admin-token-change-in-production"
  
  # OpenAI API Key - MUST BE SET FROM ENVIRONMENT VARIABLE
  # This is a placeholder - the actual key should be injected at runtime
  OPENAI_API_KEY: "${OPENAI_API_KEY}"