apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-paralegal-ui
  namespace: ai-paralegal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-paralegal-ui
  template:
    metadata:
      labels:
        app: ai-paralegal-ui
    spec:
      containers:
      - name: ui
        image: localhost:5000/ai-paralegal-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        # UI Configuration
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        
        # API Configuration - pointing to internal backend service
        - name: NEXT_PUBLIC_API_URL
          value: "http://ai-paralegal-service"
        
        # Additional environment variables from ConfigMap
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: ai-paralegal-config
              key: APP_ENV
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        
        volumeMounts:
        - name: ui-cache
          mountPath: /app/.next/cache
      
      volumes:
      - name: ui-cache
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ai-paralegal-ui-service
  namespace: ai-paralegal
spec:
  selector:
    app: ai-paralegal-ui
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP 
