FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

RUN apk add --no-cache bash

# COPY . .

# Expose app and debugger ports
EXPOSE 3000
EXPOSE 9229
EXPOSE 9230

CMD ["npm", "run", "dev:debug"]
